name: Our Workflow
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: 디렉토리 확인
        run: ls -al

      - name: 체크아웃
        uses: actions/checkout@v3

      - name: 체크아웃 변화 확인
        run: ls -al

      - run: cat .github/workflows/checkout.yml
